CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation         VARCHAR(2000),
    category_id        BIGINT,
	created_on         TIMESTAMP WITHOUT TIME ZONE,
	description        text,
	event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT,
    location_id        BIGINT REFERENCES event_locations (id) ON DELETE CASCADE,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(16),
    title              VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS event_locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilation (
    id BIGINT,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS events_compilations (
    event          BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilation    BIGINT REFERENCES event_compilation (id) ON DELETE CASCADE
)