CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title  VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS c_event (
    id BIGINT,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    event          BIGINT REFERENCES c_event (id) ON DELETE CASCADE,
    compilation    BIGINT REFERENCES compilations (id) ON DELETE CASCADE
);
